networks:
  inter-tier:

volumes:
  db_dev_data:
  db_dev-ephimeral_data:
    driver: local
    driver_opts:
      type: 'tmpfs' # Tipo de montaje
      device: 'tmpfs' # El dispositivo a montar (literalmente 'tmpfs')
      o: 'size=500m' # Opciones de montaje: tamaño de 100MB y UID del propietario

x-db-dev-template: &db-dev-template
  image: postgres:17.5-alpine
  restart: unless-stopped
  cap_add:
    - SYS_NICE  # CAP_SYS_NICE
  env_file:
    - ./.env
  networks:
    inter-tier:
      aliases:
        - db-dev
  ports:
    - "5432:5432"
  expose:
    - 5432

services:
  db-dev:
    <<: *db-dev-template
    volumes:
      - db_dev_data:/var/lib/postgresql/data
    profiles: ['dev']

  db-dev-ephimeral:
    <<: *db-dev-template
    volumes:
      - db_dev-ephimeral_data:/var/lib/postgresql/data
    profiles: ['dev-ephimeral', 'test']

  dbmate:
    image: ghcr.io/amacneil/dbmate
    networks:
      - inter-tier
    volumes:
      - ./def:/db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-dev:5432/${POSTGRES_DB}?sslmode=disable

  # db-prod:
  #   profiles: ['prod']
