networks:
  inter-tier:
    external: true
    name: ciie-test

services:
  rosbridge:
    build: .
    restart: unless-stopped
    networks:
      inter-tier:
        aliases:
          - rosbridge
    ports:
      - "9090:9090"
    environment:
      - ROS_DOMAIN_ID=0
    command: >
      ros2 launch /ros_bridge_ws/launch/bridge.launch.py
    profiles: ['dev']

  rosbridge-demo:
    build: .
    restart: unless-stopped
    networks:
      inter-tier:
        aliases:
          - rosbridge
    ports:
      - "9090:9090"
    environment:
      - ROS_DOMAIN_ID=0
      - DEMO_ROBOT_IDS=a0e1f2a3-b4c5-d6e7-f8a9-b0c1d2e3f4a5
    command: >
      ros2 launch /ros_bridge_ws/launch/bridge.launch.py demo:=true
    profiles: ['demo']
